"""rename_ts_code_to_third_code_in_stock_daily

Revision ID: 0703b1d6e4ba
Revises: 6780a3fcb624
Create Date: 2026-02-07 17:20:10.850006

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0703b1d6e4ba'
down_revision = '6780a3fcb624'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('stock_daily', 'ts_code', new_column_name='third_code', existing_type=sa.String(length=20))
    
    # 索引名称也需要更新，虽然 PostgreSQL 会自动处理列重命名后的索引，但索引名不会变
    # 手动重命名索引或重建索引
    op.drop_index(op.f('ix_stock_daily_ts_code'), table_name='stock_daily')
    op.create_index(op.f('ix_stock_daily_third_code'), 'stock_daily', ['third_code'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_stock_daily_third_code'), table_name='stock_daily')
    op.create_index(op.f('ix_stock_daily_ts_code'), 'stock_daily', ['ts_code'], unique=False)
    
    op.alter_column('stock_daily', 'third_code', new_column_name='ts_code', existing_type=sa.String(length=20))
    # ### end Alembic commands ###
