"""create stock_finance table

Revision ID: 5101fd6027e4
Revises: ed78ad770cbc
Create Date: 2026-02-08 12:20:51.741147

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5101fd6027e4'
down_revision = 'ed78ad770cbc'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stock_finance',
    sa.Column('third_code', sa.String(length=20), nullable=False, comment='第三方代码'),
    sa.Column('ann_date', sa.Date(), nullable=False, comment='公告日期'),
    sa.Column('end_date', sa.Date(), nullable=False, comment='报告期'),
    sa.Column('eps', sa.Float(), nullable=True, comment='基本每股收益'),
    sa.Column('dt_eps', sa.Float(), nullable=True, comment='稀释每股收益'),
    sa.Column('total_revenue_ps', sa.Float(), nullable=True, comment='每股营业总收入'),
    sa.Column('revenue_ps', sa.Float(), nullable=True, comment='每股营业收入'),
    sa.Column('capital_rese_ps', sa.Float(), nullable=True, comment='每股资本公积'),
    sa.Column('surplus_rese_ps', sa.Float(), nullable=True, comment='每股盈余公积'),
    sa.Column('undist_profit_ps', sa.Float(), nullable=True, comment='每股未分配利润'),
    sa.Column('extra_item', sa.Float(), nullable=True, comment='非经常性损益'),
    sa.Column('profit_dedt', sa.Float(), nullable=True, comment='扣除非经常性损益后的净利润'),
    sa.Column('gross_margin', sa.Float(), nullable=True, comment='毛利率'),
    sa.Column('current_ratio', sa.Float(), nullable=True, comment='流动比率'),
    sa.Column('quick_ratio', sa.Float(), nullable=True, comment='速动比率'),
    sa.Column('cash_ratio', sa.Float(), nullable=True, comment='保守速动比率'),
    sa.Column('inv_turn', sa.Float(), nullable=True, comment='存货周转率'),
    sa.Column('arturn', sa.Float(), nullable=True, comment='应收账款周转率'),
    sa.Column('ca_turn', sa.Float(), nullable=True, comment='流动资产周转率'),
    sa.Column('fa_turn', sa.Float(), nullable=True, comment='固定资产周转率'),
    sa.Column('assets_turn', sa.Float(), nullable=True, comment='总资产周转率'),
    sa.Column('op_income', sa.Float(), nullable=True, comment='经营活动净收益'),
    sa.Column('value_change_profit', sa.Float(), nullable=True, comment='价值变动净收益'),
    sa.Column('interst_income', sa.Float(), nullable=True, comment='利息费用'),
    sa.Column('daa', sa.Float(), nullable=True, comment='资产负债率'),
    sa.Column('ebit', sa.Float(), nullable=True, comment='息税前利润'),
    sa.Column('ebitda', sa.Float(), nullable=True, comment='息税折旧摊销前利润'),
    sa.Column('fcff', sa.Float(), nullable=True, comment='企业自由现金流量'),
    sa.Column('fcfe', sa.Float(), nullable=True, comment='股权自由现金流量'),
    sa.Column('current_ex_interest', sa.Float(), nullable=True, comment='无息流动负债'),
    sa.Column('noncurrent_ex_interest', sa.Float(), nullable=True, comment='无息非流动负债'),
    sa.Column('interestdebt', sa.Float(), nullable=True, comment='带息债务'),
    sa.Column('netdebt', sa.Float(), nullable=True, comment='净债务'),
    sa.Column('tangible_asset', sa.Float(), nullable=True, comment='有形资产'),
    sa.Column('working_capital', sa.Float(), nullable=True, comment='营运资金'),
    sa.Column('networking_capital', sa.Float(), nullable=True, comment='营运流动资本'),
    sa.Column('invest_capital', sa.Float(), nullable=True, comment='全部投入资本'),
    sa.Column('retained_earnings', sa.Float(), nullable=True, comment='留存收益'),
    sa.Column('diluted2_eps', sa.Float(), nullable=True, comment='期末摊薄每股收益'),
    sa.Column('bps', sa.Float(), nullable=True, comment='每股净资产'),
    sa.Column('ocfps', sa.Float(), nullable=True, comment='每股经营活动产生的现金流量净额'),
    sa.Column('retainedps', sa.Float(), nullable=True, comment='每股留存收益'),
    sa.Column('cfps', sa.Float(), nullable=True, comment='每股现金流量净额'),
    sa.Column('ebit_ps', sa.Float(), nullable=True, comment='每股息税前利润'),
    sa.Column('fcff_ps', sa.Float(), nullable=True, comment='每股企业自由现金流量'),
    sa.Column('fcfe_ps', sa.Float(), nullable=True, comment='每股股权自由现金流量'),
    sa.Column('source', sa.String(length=20), nullable=True, comment='数据来源'),
    sa.PrimaryKeyConstraint('third_code', 'ann_date', 'end_date')
    )
    op.create_index(op.f('ix_stock_finance_ann_date'), 'stock_finance', ['ann_date'], unique=False)
    op.create_index(op.f('ix_stock_finance_end_date'), 'stock_finance', ['end_date'], unique=False)
    op.create_index(op.f('ix_stock_finance_third_code'), 'stock_finance', ['third_code'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_stock_finance_third_code'), table_name='stock_finance')
    op.drop_index(op.f('ix_stock_finance_end_date'), table_name='stock_finance')
    op.drop_index(op.f('ix_stock_finance_ann_date'), table_name='stock_finance')
    op.drop_table('stock_finance')
    # ### end Alembic commands ###
