"""add_stock_daily_table

Revision ID: 6780a3fcb624
Revises: f39fe391c6c8
Create Date: 2026-02-07 17:01:48.062094

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6780a3fcb624'
down_revision = 'f39fe391c6c8'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stock_daily',
    sa.Column('ts_code', sa.String(length=20), nullable=False, comment='TS代码'),
    sa.Column('trade_date', sa.Date(), nullable=False, comment='交易日期'),
    sa.Column('open', sa.Float(), nullable=True, comment='开盘价'),
    sa.Column('high', sa.Float(), nullable=True, comment='最高价'),
    sa.Column('low', sa.Float(), nullable=True, comment='最低价'),
    sa.Column('close', sa.Float(), nullable=True, comment='收盘价'),
    sa.Column('pre_close', sa.Float(), nullable=True, comment='昨收价'),
    sa.Column('change', sa.Float(), nullable=True, comment='涨跌额'),
    sa.Column('pct_chg', sa.Float(), nullable=True, comment='涨跌幅'),
    sa.Column('vol', sa.Float(), nullable=True, comment='成交量'),
    sa.Column('amount', sa.Float(), nullable=True, comment='成交额'),
    sa.Column('source', sa.String(length=20), nullable=True, comment='数据来源'),
    sa.PrimaryKeyConstraint('ts_code', 'trade_date')
    )
    op.create_index(op.f('ix_stock_daily_trade_date'), 'stock_daily', ['trade_date'], unique=False)
    op.create_index(op.f('ix_stock_daily_ts_code'), 'stock_daily', ['ts_code'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_stock_daily_ts_code'), table_name='stock_daily')
    op.drop_index(op.f('ix_stock_daily_trade_date'), table_name='stock_daily')
    op.drop_table('stock_daily')
    # ### end Alembic commands ###
