"""create_stock_info_table

Revision ID: 9b599745e787
Revises: 
Create Date: 2026-02-07 15:58:31.048351

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9b599745e787'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stock_info',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('third_code', sa.String(length=20), nullable=False, comment='第三方代码'),
    sa.Column('symbol', sa.String(length=10), nullable=False, comment='股票代码'),
    sa.Column('name', sa.String(length=100), nullable=False, comment='股票名称'),
    sa.Column('area', sa.String(length=50), nullable=True, comment='所在地域'),
    sa.Column('industry', sa.String(length=50), nullable=True, comment='所属行业'),
    sa.Column('market', sa.String(length=20), nullable=True, comment='市场类型'),
    sa.Column('list_date', sa.Date(), nullable=True, comment='上市日期'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stock_info_id'), 'stock_info', ['id'], unique=False)
    op.create_index(op.f('ix_stock_info_industry'), 'stock_info', ['industry'], unique=False)
    op.create_index(op.f('ix_stock_info_market'), 'stock_info', ['market'], unique=False)
    op.create_index(op.f('ix_stock_info_symbol'), 'stock_info', ['symbol'], unique=True)
    op.create_index(op.f('ix_stock_info_third_code'), 'stock_info', ['third_code'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_stock_info_third_code'), table_name='stock_info')
    op.drop_index(op.f('ix_stock_info_symbol'), table_name='stock_info')
    op.drop_index(op.f('ix_stock_info_market'), table_name='stock_info')
    op.drop_index(op.f('ix_stock_info_industry'), table_name='stock_info')
    op.drop_index(op.f('ix_stock_info_id'), table_name='stock_info')
    op.drop_table('stock_info')
    # ### end Alembic commands ###
