"""update stock_finance table with full fields

Revision ID: d25e5d13455c
Revises: 5101fd6027e4
Create Date: 2026-02-08 13:38:11.371397

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd25e5d13455c'
down_revision = '5101fd6027e4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stock_finance', sa.Column('ar_turn', sa.Float(), nullable=True, comment='应收账款周转率'))
    op.add_column('stock_finance', sa.Column('invturn_days', sa.Float(), nullable=True, comment='存货周转天数'))
    op.add_column('stock_finance', sa.Column('arturn_days', sa.Float(), nullable=True, comment='应收账款周转天数'))
    op.add_column('stock_finance', sa.Column('valuechange_income', sa.Float(), nullable=True, comment='价值变动净收益'))
    op.add_column('stock_finance', sa.Column('current_exint', sa.Float(), nullable=True, comment='无息流动负债'))
    op.add_column('stock_finance', sa.Column('noncurrent_exint', sa.Float(), nullable=True, comment='无息非流动负债'))
    op.add_column('stock_finance', sa.Column('netprofit_margin', sa.Float(), nullable=True, comment='销售净利率'))
    op.add_column('stock_finance', sa.Column('grossprofit_margin', sa.Float(), nullable=True, comment='销售毛利率'))
    op.add_column('stock_finance', sa.Column('cogs_of_sales', sa.Float(), nullable=True, comment='销售成本率'))
    op.add_column('stock_finance', sa.Column('expense_of_sales', sa.Float(), nullable=True, comment='销售期间费用率'))
    op.add_column('stock_finance', sa.Column('profit_to_gr', sa.Float(), nullable=True, comment='净利润/营业总收入'))
    op.add_column('stock_finance', sa.Column('saleexp_to_gr', sa.Float(), nullable=True, comment='销售费用/营业总收入'))
    op.add_column('stock_finance', sa.Column('adminexp_of_gr', sa.Float(), nullable=True, comment='管理费用/营业总收入'))
    op.add_column('stock_finance', sa.Column('finaexp_of_gr', sa.Float(), nullable=True, comment='财务费用/营业总收入'))
    op.add_column('stock_finance', sa.Column('impai_ttm', sa.Float(), nullable=True, comment='资产减值损失/营业总收入'))
    op.add_column('stock_finance', sa.Column('gc_of_gr', sa.Float(), nullable=True, comment='营业总成本/营业总收入'))
    op.add_column('stock_finance', sa.Column('op_of_gr', sa.Float(), nullable=True, comment='营业利润/营业总收入'))
    op.add_column('stock_finance', sa.Column('ebit_of_gr', sa.Float(), nullable=True, comment='息税前利润/营业总收入'))
    op.add_column('stock_finance', sa.Column('roe', sa.Float(), nullable=True, comment='净资产收益率'))
    op.add_column('stock_finance', sa.Column('roe_waa', sa.Float(), nullable=True, comment='加权平均净资产收益率'))
    op.add_column('stock_finance', sa.Column('roe_dt', sa.Float(), nullable=True, comment='净资产收益率(扣除非经常损益)'))
    op.add_column('stock_finance', sa.Column('roa', sa.Float(), nullable=True, comment='总资产报酬率'))
    op.add_column('stock_finance', sa.Column('npta', sa.Float(), nullable=True, comment='总资产净利润'))
    op.add_column('stock_finance', sa.Column('roic', sa.Float(), nullable=True, comment='投入资本回报率'))
    op.add_column('stock_finance', sa.Column('roe_yearly', sa.Float(), nullable=True, comment='年化净资产收益率'))
    op.add_column('stock_finance', sa.Column('roa2_yearly', sa.Float(), nullable=True, comment='年化总资产报酬率'))
    op.add_column('stock_finance', sa.Column('roe_avg', sa.Float(), nullable=True, comment='平均净资产收益率'))
    op.add_column('stock_finance', sa.Column('opincome_of_ebt', sa.Float(), nullable=True, comment='经营活动净收益/利润总额'))
    op.add_column('stock_finance', sa.Column('investincome_of_ebt', sa.Float(), nullable=True, comment='价值变动净收益/利润总额'))
    op.add_column('stock_finance', sa.Column('n_op_profit_of_ebt', sa.Float(), nullable=True, comment='营业外收支净额/利润总额'))
    op.add_column('stock_finance', sa.Column('tax_to_ebt', sa.Float(), nullable=True, comment='所得税/利润总额'))
    op.add_column('stock_finance', sa.Column('dtprofit_to_profit', sa.Float(), nullable=True, comment='扣除非经常损益后的净利润/净利润'))
    op.add_column('stock_finance', sa.Column('salescash_to_or', sa.Float(), nullable=True, comment='销售商品提供劳务收到的现金/营业收入'))
    op.add_column('stock_finance', sa.Column('ocf_to_or', sa.Float(), nullable=True, comment='经营活动产生的现金流量净额/营业收入'))
    op.add_column('stock_finance', sa.Column('ocf_to_opincome', sa.Float(), nullable=True, comment='经营活动产生的现金流量净额/经营活动净收益'))
    op.add_column('stock_finance', sa.Column('capitalized_to_da', sa.Float(), nullable=True, comment='资本支出/折旧和摊销'))
    op.add_column('stock_finance', sa.Column('debt_to_assets', sa.Float(), nullable=True, comment='资产负债率'))
    op.add_column('stock_finance', sa.Column('assets_to_eqt', sa.Float(), nullable=True, comment='权益乘数'))
    op.add_column('stock_finance', sa.Column('dp_assets_to_eqt', sa.Float(), nullable=True, comment='权益乘数(杜邦分析)'))
    op.add_column('stock_finance', sa.Column('ca_to_assets', sa.Float(), nullable=True, comment='流动资产/总资产'))
    op.add_column('stock_finance', sa.Column('nca_to_assets', sa.Float(), nullable=True, comment='非流动资产/总资产'))
    op.add_column('stock_finance', sa.Column('tbassets_to_totalassets', sa.Float(), nullable=True, comment='有形资产/总资产'))
    op.add_column('stock_finance', sa.Column('int_to_talcap', sa.Float(), nullable=True, comment='带息债务/全部投入资本'))
    op.add_column('stock_finance', sa.Column('eqt_to_talcapital', sa.Float(), nullable=True, comment='归属于母公司的股东权益/全部投入资本'))
    op.add_column('stock_finance', sa.Column('currentdebt_to_debt', sa.Float(), nullable=True, comment='流动负债/负债合计'))
    op.add_column('stock_finance', sa.Column('longdeb_to_debt', sa.Float(), nullable=True, comment='非流动负债/负债合计'))
    op.add_column('stock_finance', sa.Column('ocf_to_shortdebt', sa.Float(), nullable=True, comment='经营活动产生的现金流量净额/流动负债'))
    op.add_column('stock_finance', sa.Column('debt_to_eqt', sa.Float(), nullable=True, comment='产权比率'))
    op.alter_column('stock_finance', 'daa',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment='折旧与摊销',
               existing_comment='资产负债率',
               existing_nullable=True)
    op.drop_column('stock_finance', 'noncurrent_ex_interest')
    op.drop_column('stock_finance', 'current_ex_interest')
    op.drop_column('stock_finance', 'arturn')
    op.drop_column('stock_finance', 'value_change_profit')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stock_finance', sa.Column('value_change_profit', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True, comment='价值变动净收益'))
    op.add_column('stock_finance', sa.Column('arturn', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True, comment='应收账款周转率'))
    op.add_column('stock_finance', sa.Column('current_ex_interest', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True, comment='无息流动负债'))
    op.add_column('stock_finance', sa.Column('noncurrent_ex_interest', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True, comment='无息非流动负债'))
    op.alter_column('stock_finance', 'daa',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment='资产负债率',
               existing_comment='折旧与摊销',
               existing_nullable=True)
    op.drop_column('stock_finance', 'debt_to_eqt')
    op.drop_column('stock_finance', 'ocf_to_shortdebt')
    op.drop_column('stock_finance', 'longdeb_to_debt')
    op.drop_column('stock_finance', 'currentdebt_to_debt')
    op.drop_column('stock_finance', 'eqt_to_talcapital')
    op.drop_column('stock_finance', 'int_to_talcap')
    op.drop_column('stock_finance', 'tbassets_to_totalassets')
    op.drop_column('stock_finance', 'nca_to_assets')
    op.drop_column('stock_finance', 'ca_to_assets')
    op.drop_column('stock_finance', 'dp_assets_to_eqt')
    op.drop_column('stock_finance', 'assets_to_eqt')
    op.drop_column('stock_finance', 'debt_to_assets')
    op.drop_column('stock_finance', 'capitalized_to_da')
    op.drop_column('stock_finance', 'ocf_to_opincome')
    op.drop_column('stock_finance', 'ocf_to_or')
    op.drop_column('stock_finance', 'salescash_to_or')
    op.drop_column('stock_finance', 'dtprofit_to_profit')
    op.drop_column('stock_finance', 'tax_to_ebt')
    op.drop_column('stock_finance', 'n_op_profit_of_ebt')
    op.drop_column('stock_finance', 'investincome_of_ebt')
    op.drop_column('stock_finance', 'opincome_of_ebt')
    op.drop_column('stock_finance', 'roe_avg')
    op.drop_column('stock_finance', 'roa2_yearly')
    op.drop_column('stock_finance', 'roe_yearly')
    op.drop_column('stock_finance', 'roic')
    op.drop_column('stock_finance', 'npta')
    op.drop_column('stock_finance', 'roa')
    op.drop_column('stock_finance', 'roe_dt')
    op.drop_column('stock_finance', 'roe_waa')
    op.drop_column('stock_finance', 'roe')
    op.drop_column('stock_finance', 'ebit_of_gr')
    op.drop_column('stock_finance', 'op_of_gr')
    op.drop_column('stock_finance', 'gc_of_gr')
    op.drop_column('stock_finance', 'impai_ttm')
    op.drop_column('stock_finance', 'finaexp_of_gr')
    op.drop_column('stock_finance', 'adminexp_of_gr')
    op.drop_column('stock_finance', 'saleexp_to_gr')
    op.drop_column('stock_finance', 'profit_to_gr')
    op.drop_column('stock_finance', 'expense_of_sales')
    op.drop_column('stock_finance', 'cogs_of_sales')
    op.drop_column('stock_finance', 'grossprofit_margin')
    op.drop_column('stock_finance', 'netprofit_margin')
    op.drop_column('stock_finance', 'noncurrent_exint')
    op.drop_column('stock_finance', 'current_exint')
    op.drop_column('stock_finance', 'valuechange_income')
    op.drop_column('stock_finance', 'arturn_days')
    op.drop_column('stock_finance', 'invturn_days')
    op.drop_column('stock_finance', 'ar_turn')
    # ### end Alembic commands ###
