"""add_fields_to_stock_daily

Revision ID: ed78ad770cbc
Revises: 0703b1d6e4ba
Create Date: 2026-02-07 20:23:19.204899

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ed78ad770cbc'
down_revision = '0703b1d6e4ba'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stock_daily', sa.Column('adj_factor', sa.Float(), nullable=True, comment='复权因子'))
    op.add_column('stock_daily', sa.Column('turnover_rate', sa.Float(), nullable=True, comment='换手率'))
    op.add_column('stock_daily', sa.Column('turnover_rate_f', sa.Float(), nullable=True, comment='换手率(自由流通股)'))
    op.add_column('stock_daily', sa.Column('volume_ratio', sa.Float(), nullable=True, comment='量比'))
    op.add_column('stock_daily', sa.Column('pe', sa.Float(), nullable=True, comment='市盈率'))
    op.add_column('stock_daily', sa.Column('pe_ttm', sa.Float(), nullable=True, comment='市盈率TTM'))
    op.add_column('stock_daily', sa.Column('pb', sa.Float(), nullable=True, comment='市净率'))
    op.add_column('stock_daily', sa.Column('ps', sa.Float(), nullable=True, comment='市销率'))
    op.add_column('stock_daily', sa.Column('ps_ttm', sa.Float(), nullable=True, comment='市销率TTM'))
    op.add_column('stock_daily', sa.Column('dv_ratio', sa.Float(), nullable=True, comment='股息率'))
    op.add_column('stock_daily', sa.Column('dv_ttm', sa.Float(), nullable=True, comment='股息率TTM'))
    op.add_column('stock_daily', sa.Column('total_share', sa.Float(), nullable=True, comment='总股本'))
    op.add_column('stock_daily', sa.Column('float_share', sa.Float(), nullable=True, comment='流通股本'))
    op.add_column('stock_daily', sa.Column('free_share', sa.Float(), nullable=True, comment='自由流通股本'))
    op.add_column('stock_daily', sa.Column('total_mv', sa.Float(), nullable=True, comment='总市值'))
    op.add_column('stock_daily', sa.Column('circ_mv', sa.Float(), nullable=True, comment='流通市值'))
    op.alter_column('stock_daily', 'third_code',
               existing_type=sa.VARCHAR(length=20),
               comment='第三方代码',
               existing_comment='TS代码',
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('stock_daily', 'third_code',
               existing_type=sa.VARCHAR(length=20),
               comment='TS代码',
               existing_comment='第三方代码',
               existing_nullable=False)
    op.drop_column('stock_daily', 'circ_mv')
    op.drop_column('stock_daily', 'total_mv')
    op.drop_column('stock_daily', 'free_share')
    op.drop_column('stock_daily', 'float_share')
    op.drop_column('stock_daily', 'total_share')
    op.drop_column('stock_daily', 'dv_ttm')
    op.drop_column('stock_daily', 'dv_ratio')
    op.drop_column('stock_daily', 'ps_ttm')
    op.drop_column('stock_daily', 'ps')
    op.drop_column('stock_daily', 'pb')
    op.drop_column('stock_daily', 'pe_ttm')
    op.drop_column('stock_daily', 'pe')
    op.drop_column('stock_daily', 'volume_ratio')
    op.drop_column('stock_daily', 'turnover_rate_f')
    op.drop_column('stock_daily', 'turnover_rate')
    op.drop_column('stock_daily', 'adj_factor')
    # ### end Alembic commands ###
