"""add_more_fields_and_source_to_stock_info

Revision ID: f39fe391c6c8
Revises: 9b599745e787
Create Date: 2026-02-07 16:16:03.001188

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f39fe391c6c8'
down_revision = '9b599745e787'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stock_info', sa.Column('fullname', sa.String(length=200), nullable=True, comment='股票全称'))
    op.add_column('stock_info', sa.Column('enname', sa.String(length=200), nullable=True, comment='英文全称'))
    op.add_column('stock_info', sa.Column('cnspell', sa.String(length=50), nullable=True, comment='拼音缩写'))
    op.add_column('stock_info', sa.Column('exchange', sa.String(length=20), nullable=True, comment='交易所代码'))
    op.add_column('stock_info', sa.Column('curr_type', sa.String(length=20), nullable=True, comment='交易货币'))
    op.add_column('stock_info', sa.Column('list_status', sa.String(length=10), nullable=True, comment='上市状态 L上市 D退市 P暂停上市'))
    op.add_column('stock_info', sa.Column('delist_date', sa.Date(), nullable=True, comment='退市日期'))
    op.add_column('stock_info', sa.Column('is_hs', sa.String(length=10), nullable=True, comment='是否沪深港通标的，N否 H沪股通 S深股通'))
    op.add_column('stock_info', sa.Column('source', sa.String(length=20), nullable=True, comment='数据来源'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('stock_info', 'source')
    op.drop_column('stock_info', 'is_hs')
    op.drop_column('stock_info', 'delist_date')
    op.drop_column('stock_info', 'list_status')
    op.drop_column('stock_info', 'curr_type')
    op.drop_column('stock_info', 'exchange')
    op.drop_column('stock_info', 'cnspell')
    op.drop_column('stock_info', 'enname')
    op.drop_column('stock_info', 'fullname')
    # ### end Alembic commands ###
